[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "imdb-spanish-sentiment"
version = "0.1.0"
description = "Análisis de sentimientos sobre IMDB Movie Reviews en español con MLflow y FastAPI."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

